title: IAAC LTD
description: Landing page for IAAC LTD - O365 and Azure Consultancy
social_link: twitter
social_username: IAAC-LTD
github_repo: IAAC
github_username: IAAC
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /web3
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow

theme: jekyll-theme-slate